spring.application.name=PaymentIngestor
# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# KAFKA - PRODUCER CONFIG
# ===============================

# Kafka broker address (from docker-compose)
spring.kafka.bootstrap-servers=localhost:9092

# Key serializer (String for accountId partition key)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Value serializer (JSON for PaymentRequest)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Ensure all replicas acknowledge (strong durability, slightly higher latency)
spring.kafka.producer.acks=all

# Enable idempotence to prevent duplicate messages on retry
spring.kafka.producer.properties.enable.idempotence=true

# Wait up to 5ms to batch messages (improves throughput with minimal latency impact)
spring.kafka.producer.linger.ms=5

# Compress messages to reduce network usage (good trade-off for throughput)
spring.kafka.producer.compression-type=snappy